<?php

declare(strict_types=1);
/**
 * Repository for active-job lifecycle persistence.
 *
 * Implements Phase 1a + 1b of the resumable-background-jobs feature (t200/t201).
 * The DB row is the source of truth; the transient is the fast-path cache.
 *
 * Lifecycle:
 *   handle_run()    → create()   (status = processing)
 *   handle_process()→ update()   (status = awaiting_confirmation | complete | error)
 *   resume_job()    → update()   (status = processing, on re-dispatch)
 *   handle_job_status() fallback → get()  (when transient is gone)
 *   handle_job_status() on complete/error delivery → delete()
 *
 * @package GratisAiAgent
 * @license GPL-2.0-or-later
 */

namespace GratisAiAgent\Repositories;

use GratisAiAgent\Core\Database;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Handles persistence for background-job lifecycle records.
 *
 * The table mirrors the shape of the job transient so that a DB read can
 * reconstruct an adequate response when the transient has expired.
 */
class ActiveJobRepository {

	/**
	 * Return the fully-qualified table name.
	 */
	public static function table_name(): string {
		global $wpdb;
		/** @var \wpdb $wpdb */
		return $wpdb->prefix . 'gratis_ai_agent_active_jobs';
	}

	// ─── Write operations ─────────────────────────────────────────────────────

	/**
	 * Create a new active-job row when a job is first enqueued.
	 *
	 * @param string $job_id     UUID generated by wp_generate_uuid4().
	 * @param int    $session_id WordPress session ID, or 0 for sessionless jobs.
	 * @param int    $user_id    WordPress user ID.
	 * @return bool True on success.
	 */
	public static function create( string $job_id, int $session_id, int $user_id ): bool {
		global $wpdb;
		/** @var \wpdb $wpdb */

		$now = current_time( 'mysql', true );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery -- Custom table; caching not applicable.
		$result = $wpdb->insert(
			self::table_name(),
			[
				'job_id'      => $job_id,
				'session_id'  => $session_id,
				'user_id'     => $user_id,
				'status'      => 'processing',
				'tool_calls'  => '[]',
				'created_at'  => $now,
				'updated_at'  => $now,
			],
			[ '%s', '%d', '%d', '%s', '%s', '%s', '%s' ]
		);

		return false !== $result;
	}

	/**
	 * Update status and optional payload fields for an existing job.
	 *
	 * Only non-null values in $data are written.
	 *
	 * @param string               $job_id Job UUID.
	 * @param array<string, mixed> $data   Fields to update. Recognised keys:
	 *   - status         string  (processing|awaiting_confirmation|complete|error)
	 *   - tool_calls     mixed[] JSON-serialisable array of tool-call progress entries.
	 *   - pending_tools  mixed[] JSON-serialisable pending tool descriptors.
	 *   - error_message  string  Human-readable error text.
	 *   - result_data    mixed[] Minimal result summary (session_id, model_id, etc.)
	 * @return bool True on success.
	 */
	public static function update( string $job_id, array $data ): bool {
		global $wpdb;
		/** @var \wpdb $wpdb */

		$fields  = [ 'updated_at' => current_time( 'mysql', true ) ];
		$formats = [ '%s' ];

		if ( isset( $data['status'] ) ) {
			$fields['status'] = (string) $data['status'];
			$formats[]        = '%s';
		}

		if ( isset( $data['tool_calls'] ) ) {
			$fields['tool_calls'] = wp_json_encode( $data['tool_calls'] );
			$formats[]            = '%s';
		}

		if ( isset( $data['pending_tools'] ) ) {
			$fields['pending_tools'] = wp_json_encode( $data['pending_tools'] );
			$formats[]               = '%s';
		}

		if ( isset( $data['error_message'] ) ) {
			$fields['error_message'] = (string) $data['error_message'];
			$formats[]               = '%s';
		}

		if ( isset( $data['result_data'] ) ) {
			$fields['result_data'] = wp_json_encode( $data['result_data'] );
			$formats[]             = '%s';
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table; caching not applicable.
		$result = $wpdb->update(
			self::table_name(),
			$fields,
			[ 'job_id' => $job_id ],
			$formats,
			[ '%s' ]
		);

		return false !== $result;
	}

	/**
	 * Delete the job row after the result has been delivered to the client.
	 *
	 * Mirrors the behaviour of delete_transient() in handle_job_status().
	 *
	 * @param string $job_id Job UUID.
	 * @return bool True on success.
	 */
	public static function delete( string $job_id ): bool {
		global $wpdb;
		/** @var \wpdb $wpdb */

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table; caching not applicable.
		$result = $wpdb->delete(
			self::table_name(),
			[ 'job_id' => $job_id ],
			[ '%s' ]
		);

		return false !== $result;
	}

	// ─── Read operations ──────────────────────────────────────────────────────

	/**
	 * Fetch a single job row by its UUID.
	 *
	 * Returns null when the job is not found (already delivered and deleted).
	 *
	 * @param string $job_id Job UUID.
	 * @return object|null DB row object, or null.
	 */
	public static function get( string $job_id ): ?object {
		global $wpdb;
		/** @var \wpdb $wpdb */

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Real-time job status; caching would return stale data.
		$row = $wpdb->get_row(
			$wpdb->prepare(
				'SELECT * FROM %i WHERE job_id = %s',
				self::table_name(),
				$job_id
			)
		);

		return $row instanceof \stdClass ? $row : null;
	}

	/**
	 * Get the most recent non-complete active job for a session.
	 *
	 * Used by the reconnection endpoint (Phase 1c, t202) to resume a poll
	 * loop after the user navigates back to the chat.
	 *
	 * @param int $session_id Session ID.
	 * @return object|null Job row, or null when no active job exists.
	 */
	public static function get_active_by_session( int $session_id ): ?object {
		global $wpdb;
		/** @var \wpdb $wpdb */

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Real-time job status; caching would return stale data.
		$row = $wpdb->get_row(
			$wpdb->prepare(
				"SELECT * FROM %i WHERE session_id = %d AND status IN ('processing','awaiting_confirmation') ORDER BY created_at DESC LIMIT 1",
				self::table_name(),
				$session_id
			)
		);

		return $row instanceof \stdClass ? $row : null;
	}

	// ─── Helper methods ───────────────────────────────────────────────────────

	/**
	 * Reconstruct a job-status response array from a DB row.
	 *
	 * Mirrors the shape returned by handle_job_status() so callers can treat
	 * DB-sourced and transient-sourced data identically.
	 *
	 * For 'complete' jobs the full reply and history are NOT stored in the DB
	 * (too large; already persisted in the session's messages column).  The
	 * caller should direct the frontend to reload the session instead.
	 *
	 * @param object $row DB row from get().
	 * @return array<string, mixed> Partial response array.
	 */
	public static function to_response( object $row ): array {
		$status   = (string) $row->status;
		$response = [ 'status' => $status, 'from_db' => true ];

		$tool_calls = ! empty( $row->tool_calls ) ? json_decode( $row->tool_calls, true ) : [];
		if ( is_array( $tool_calls ) && ! empty( $tool_calls ) ) {
			$response['tool_calls'] = $tool_calls;
		}

		if ( 'awaiting_confirmation' === $status ) {
			$pending = ! empty( $row->pending_tools ) ? json_decode( $row->pending_tools, true ) : [];
			if ( is_array( $pending ) ) {
				$response['pending_tools'] = $pending;
			}
		}

		if ( 'error' === $status && ! empty( $row->error_message ) ) {
			$response['message'] = $row->error_message;
		}

		if ( 'complete' === $status ) {
			$result_data = ! empty( $row->result_data ) ? json_decode( $row->result_data, true ) : [];
			if ( is_array( $result_data ) ) {
				$response = array_merge( $response, $result_data );
			}
		}

		return $response;
	}
}
